/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2013 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.remote.order.action;

import com.clover.sdk.GenericClient;

@SuppressWarnings("all")
public final class AddDiscountAction implements android.os.Parcelable, com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  public com.clover.remote.order.DisplayDiscount getDiscount() {
    return genClient.cacheGet(CacheKey.discount);
  }



  private enum CacheKey implements com.clover.sdk.ValueExtractorEnum<AddDiscountAction> {
    discount {
      @Override
      public Object extractValue(AddDiscountAction instance) {
        return instance.genClient.extractRecord("discount", com.clover.remote.order.DisplayDiscount.JSON_CREATOR);
      }
    },
    ;
  }

  private GenericClient<AddDiscountAction> genClient = new GenericClient<AddDiscountAction>(this);

  /**
   * Constructs a new empty instance.
   */
  public AddDiscountAction() { }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public AddDiscountAction(String json) throws IllegalArgumentException {
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public AddDiscountAction(org.json.JSONObject jsonObject) {
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public AddDiscountAction(AddDiscountAction src) {
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }


  @Override
  public void validate() {
    genClient.validateNull(getDiscount(), "discount");
  }

  /** Checks whether the 'discount' field is set and is not null */
  public boolean isNotNullDiscount() {
    return genClient.cacheValueIsNotNull(CacheKey.discount);
  }


  /** Checks whether the 'discount' field has been set, however the value could be null */
  public boolean hasDiscount() {
    return genClient.cacheHasKey(CacheKey.discount);
  }


  /**
   * Sets the field 'discount'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public AddDiscountAction setDiscount(com.clover.remote.order.DisplayDiscount discount) {
    return genClient.setRecord(discount, CacheKey.discount);
  }


  /** Clears the 'discount' field, the 'has' method for this field will now return false */
  public void clearDiscount() {
    genClient.clear(CacheKey.discount);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public AddDiscountAction copyChanges() {
    AddDiscountAction copy = new AddDiscountAction();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(AddDiscountAction src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new AddDiscountAction(src).getJSONObject(), src.genClient);
    }
  }

  /**
   * Gets a Bundle which can be used to get and set data attached to this instance. The attached Bundle will be
   * parcelled but not jsonified.
   */
  public android.os.Bundle getBundle() {
    return genClient.getBundle();
  }

  @Override
  public String toString() {
    return genClient.toString();
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {
    genClient.writeToParcel(dest, flags);
  }

  public static final android.os.Parcelable.Creator<AddDiscountAction> CREATOR = new android.os.Parcelable.Creator<AddDiscountAction>() {
    @Override
    public AddDiscountAction createFromParcel(android.os.Parcel in) {
      AddDiscountAction instance = new AddDiscountAction(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public AddDiscountAction[] newArray(int size) {
      return new AddDiscountAction[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<AddDiscountAction> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<AddDiscountAction>() {
    @Override
    public AddDiscountAction create(org.json.JSONObject jsonObject) {
      return new AddDiscountAction(jsonObject);
    }
  };


  public interface Constraints {

    public static final boolean DISCOUNT_IS_REQUIRED = true;

  }

}
