/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2013 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.remote.order.action;

import com.clover.sdk.GenericClient;

@SuppressWarnings("all")
public final class AddLineItemAction implements android.os.Parcelable, com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  public com.clover.remote.order.DisplayLineItem getLineItem() {
    return genClient.cacheGet(CacheKey.lineItem);
  }

  public java.lang.Boolean getTaxable() {
    return genClient.cacheGet(CacheKey.taxable);
  }



  private enum CacheKey implements com.clover.sdk.ValueExtractorEnum<AddLineItemAction> {
    lineItem {
      @Override
      public Object extractValue(AddLineItemAction instance) {
        return instance.genClient.extractRecord("lineItem", com.clover.remote.order.DisplayLineItem.JSON_CREATOR);
      }
    },
    taxable {
      @Override
      public Object extractValue(AddLineItemAction instance) {
        return instance.genClient.extractOther("taxable", java.lang.Boolean.class);
      }
    },
    ;
  }

  private GenericClient<AddLineItemAction> genClient = new GenericClient<AddLineItemAction>(this);

  /**
   * Constructs a new empty instance.
   */
  public AddLineItemAction() { }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public AddLineItemAction(String json) throws IllegalArgumentException {
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public AddLineItemAction(org.json.JSONObject jsonObject) {
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public AddLineItemAction(AddLineItemAction src) {
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }


  @Override
  public void validate() {
    genClient.validateNull(getLineItem(), "lineItem");
  }

  /** Checks whether the 'lineItem' field is set and is not null */
  public boolean isNotNullLineItem() {
    return genClient.cacheValueIsNotNull(CacheKey.lineItem);
  }

  /** Checks whether the 'taxable' field is set and is not null */
  public boolean isNotNullTaxable() {
    return genClient.cacheValueIsNotNull(CacheKey.taxable);
  }


  /** Checks whether the 'lineItem' field has been set, however the value could be null */
  public boolean hasLineItem() {
    return genClient.cacheHasKey(CacheKey.lineItem);
  }

  /** Checks whether the 'taxable' field has been set, however the value could be null */
  public boolean hasTaxable() {
    return genClient.cacheHasKey(CacheKey.taxable);
  }


  /**
   * Sets the field 'lineItem'.
   *
   * The parameter is not copied so changes to it will be reflected in this instance and vice-versa.
   */
  public AddLineItemAction setLineItem(com.clover.remote.order.DisplayLineItem lineItem) {
    return genClient.setRecord(lineItem, CacheKey.lineItem);
  }

  /**
   * Sets the field 'taxable'.
   */
  public AddLineItemAction setTaxable(java.lang.Boolean taxable) {
    return genClient.setOther(taxable, CacheKey.taxable);
  }


  /** Clears the 'lineItem' field, the 'has' method for this field will now return false */
  public void clearLineItem() {
    genClient.clear(CacheKey.lineItem);
  }
  /** Clears the 'taxable' field, the 'has' method for this field will now return false */
  public void clearTaxable() {
    genClient.clear(CacheKey.taxable);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public AddLineItemAction copyChanges() {
    AddLineItemAction copy = new AddLineItemAction();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(AddLineItemAction src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new AddLineItemAction(src).getJSONObject(), src.genClient);
    }
  }

  /**
   * Gets a Bundle which can be used to get and set data attached to this instance. The attached Bundle will be
   * parcelled but not jsonified.
   */
  public android.os.Bundle getBundle() {
    return genClient.getBundle();
  }

  @Override
  public String toString() {
    return genClient.toString();
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {
    genClient.writeToParcel(dest, flags);
  }

  public static final android.os.Parcelable.Creator<AddLineItemAction> CREATOR = new android.os.Parcelable.Creator<AddLineItemAction>() {
    @Override
    public AddLineItemAction createFromParcel(android.os.Parcel in) {
      AddLineItemAction instance = new AddLineItemAction(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public AddLineItemAction[] newArray(int size) {
      return new AddLineItemAction[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<AddLineItemAction> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<AddLineItemAction>() {
    @Override
    public AddLineItemAction create(org.json.JSONObject jsonObject) {
      return new AddLineItemAction(jsonObject);
    }
  };


  public interface Constraints {

    public static final boolean LINEITEM_IS_REQUIRED = true;

    public static final boolean TAXABLE_IS_REQUIRED = false;

  }

}
