/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2013 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.remote.order.action;

import com.clover.sdk.GenericClient;

@SuppressWarnings("all")
public final class RemoveLineItemAction implements android.os.Parcelable, com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  public java.lang.String getLineItemId() {
    return genClient.cacheGet(CacheKey.lineItemId);
  }



  private enum CacheKey implements com.clover.sdk.ValueExtractorEnum<RemoveLineItemAction> {
    lineItemId {
      @Override
      public Object extractValue(RemoveLineItemAction instance) {
        return instance.genClient.extractOther("lineItemId", java.lang.String.class);
      }
    },
    ;
  }

  private GenericClient<RemoveLineItemAction> genClient = new GenericClient<RemoveLineItemAction>(this);

  /**
   * Constructs a new empty instance.
   */
  public RemoveLineItemAction() { }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public RemoveLineItemAction(String json) throws IllegalArgumentException {
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public RemoveLineItemAction(org.json.JSONObject jsonObject) {
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public RemoveLineItemAction(RemoveLineItemAction src) {
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }


  @Override
  public void validate() {
    genClient.validateNull(getLineItemId(), "lineItemId");
  }

  /** Checks whether the 'lineItemId' field is set and is not null */
  public boolean isNotNullLineItemId() {
    return genClient.cacheValueIsNotNull(CacheKey.lineItemId);
  }


  /** Checks whether the 'lineItemId' field has been set, however the value could be null */
  public boolean hasLineItemId() {
    return genClient.cacheHasKey(CacheKey.lineItemId);
  }


  /**
   * Sets the field 'lineItemId'.
   */
  public RemoveLineItemAction setLineItemId(java.lang.String lineItemId) {
    return genClient.setOther(lineItemId, CacheKey.lineItemId);
  }


  /** Clears the 'lineItemId' field, the 'has' method for this field will now return false */
  public void clearLineItemId() {
    genClient.clear(CacheKey.lineItemId);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public RemoveLineItemAction copyChanges() {
    RemoveLineItemAction copy = new RemoveLineItemAction();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(RemoveLineItemAction src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new RemoveLineItemAction(src).getJSONObject(), src.genClient);
    }
  }

  /**
   * Gets a Bundle which can be used to get and set data attached to this instance. The attached Bundle will be
   * parcelled but not jsonified.
   */
  public android.os.Bundle getBundle() {
    return genClient.getBundle();
  }

  @Override
  public String toString() {
    return genClient.toString();
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {
    genClient.writeToParcel(dest, flags);
  }

  public static final android.os.Parcelable.Creator<RemoveLineItemAction> CREATOR = new android.os.Parcelable.Creator<RemoveLineItemAction>() {
    @Override
    public RemoveLineItemAction createFromParcel(android.os.Parcel in) {
      RemoveLineItemAction instance = new RemoveLineItemAction(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public RemoveLineItemAction[] newArray(int size) {
      return new RemoveLineItemAction[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<RemoveLineItemAction> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<RemoveLineItemAction>() {
    @Override
    public RemoveLineItemAction create(org.json.JSONObject jsonObject) {
      return new RemoveLineItemAction(jsonObject);
    }
  };


  public interface Constraints {

    public static final boolean LINEITEMID_IS_REQUIRED = true;

  }

}
