package com.clover.remote.client.clovergo.event;

/**
 * Created by Akhani, Avdhesh on 4/19/17.
 */

public enum CardReaderEventType {
    CARD_SWIPED, CARD_TAPPED,SWIPE_FAILED, EMV_CARD_SWIPED_ERROR, EMV_DIP_FAILED_3_ATTEMPTS, EMV_CARD_DIP_FAILED, EMV_CARD_INSERTED,
    CLEAR_AID_PK_COMPLETE,AID_FLUSH_COMPLETE,PUBLIC_KEY_FLUSH_COMPLETE,DOL_FLUSH_COMPLETE,INITIALIZATION_COMPLETE,CALIBRATION_IN_PROGRESS,
    EMV_CARD_REMOVED,PAIRING_COMPLETE,CONTACTLESS_FAILED_TRY_AGAIN,CUSTOMER_VALIDATION
}
