/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

package com.clover.remote.client.messages;

import com.clover.sdk.internal.PayIntent;

/** A authorization request */
@SuppressWarnings(value="unused")
public class AuthRequest extends TransactionRequest {

  private Boolean disableCashback = null;
  private Long taxAmount = null;
  private Boolean allowOfflinePayment = null;
  private Boolean approveOfflinePaymentWithoutPrompt = null;

  public AuthRequest(long amount, String externalId) {
    super(amount, externalId);
  }
  /**
  * Set the field value
  * Do not allow cash back
  *
  */
  public void setDisableCashback(Boolean disableCashback) {
    this.disableCashback = disableCashback;
  }

  /**
  * Get the field value
  * Do not allow cash back
  */
  public Boolean getDisableCashback() {
    return this.disableCashback;
  }  
  /**
  * Set the field value
  * Amount paid in tips
  *
  */
  public void setTaxAmount(Long taxAmount) {
    this.taxAmount = taxAmount;
  }

  /**
  * Get the field value
  * Amount paid in tips
  */
  public Long getTaxAmount() {
    return this.taxAmount;
  }  
  /**
  * Set the field value
  * If true then offline payments can be accepted
  *
  */
  public void setAllowOfflinePayment(Boolean allowOfflinePayment) {
    this.allowOfflinePayment = allowOfflinePayment;
  }

  /**
  * Get the field value
  * If true then offline payments can be accepted
  */
  public Boolean getAllowOfflinePayment() {
    return this.allowOfflinePayment;
  }  
  /**
  * Set the field value
  * If true then offline payments will be approved without a prompt.  Currently must be true.
  *
  */
  public void setApproveOfflinePaymentWithoutPrompt(Boolean approveOfflinePaymentWithoutPrompt) {
    this.approveOfflinePaymentWithoutPrompt = approveOfflinePaymentWithoutPrompt;
  }

  /**
  * Get the field value
  * If true then offline payments will be approved without a prompt.  Currently must be true.
  */
  public Boolean getApproveOfflinePaymentWithoutPrompt() {
    return this.approveOfflinePaymentWithoutPrompt;
  }

  @Override public PayIntent.TransactionType getType() {
    return PayIntent.TransactionType.PAYMENT;
  }
}
