package com.clover.remote.client.lib.example;

public interface AppConstants {
  String CONFIG_TYPE_LAN = "LAN";
  String CONFIG_TYPE_GO = "GO";
  String CONFIG_TYPE_USB = "USB";
  String CONFIG_TYPE_WS = "WS";

  String PAYMENT_TYPE_KEYED = "KEYED";
  String PAYMENT_TYPE_RP450 = "RP450";
  String PAYMENT_TYPE_RP350 = "RP350";

  String TRANSACTION_TYPE_ARG = "TRANSACTION_TYPE_ARG";
  String TRANSACTION_TYPE_AUTH = "TRANSACTION_TYPE_AUTH";
  String TRANSACTION_TYPE_SALE = "TRANSACTION_TYPE_SALE";

  String FRAGMENT_PAYMENT_METHODS = "FRAGMENT_PAYMENT_METHODS";
}
