/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */


/*
 * Copyright (C) 2013 Clover Network, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.clover.remote.order.operation;

import com.clover.sdk.GenericClient;

@SuppressWarnings("all")
public final class LineItemsDeletedOperation implements android.os.Parcelable, com.clover.sdk.v3.Validator, com.clover.sdk.JSONifiable {

  public java.util.List<String> getIds() {
    return genClient.cacheGet(CacheKey.ids);
  }

  public String getOrderId() {
    return genClient.cacheGet(CacheKey.orderId);
  }



  private enum CacheKey implements com.clover.sdk.ValueExtractorEnum<LineItemsDeletedOperation> {
    ids {
      @Override
      public Object extractValue(LineItemsDeletedOperation instance) {
        return instance.genClient.extractListOther("ids", String.class);
      }
    },
    orderId {
      @Override
      public Object extractValue(LineItemsDeletedOperation instance) {
        return instance.genClient.extractOther("orderId", String.class);
      }
    },
    ;
  }

  private GenericClient<LineItemsDeletedOperation> genClient = new GenericClient<LineItemsDeletedOperation>(this);

  /**
   * Constructs a new empty instance.
   */
  public LineItemsDeletedOperation() { }

  /**
   * Constructs a new instance from the given JSON String.
   */
  public LineItemsDeletedOperation(String json) throws IllegalArgumentException {
    try {
      genClient.setJsonObject(new org.json.JSONObject(json));
    } catch (org.json.JSONException e) {
      throw new IllegalArgumentException("invalid json", e);
    }
  }

  /**
   * Construct a new instance backed by the given JSONObject, the parameter is not copied so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public LineItemsDeletedOperation(org.json.JSONObject jsonObject) {
    genClient.setJsonObject(jsonObject);
  }

  /**
   * Constructs a new instance that is a deep copy of the source instance. It does not copy the bundle or changelog.
   */
  public LineItemsDeletedOperation(LineItemsDeletedOperation src) {
    if (src.genClient.getJsonObject() != null) {
      genClient.setJsonObject(com.clover.sdk.v3.JsonHelper.deepCopy(src.genClient.getJSONObject()));
    }
  }

  /**
   * Returns the internal JSONObject backing this instance, the return value is not a copy so changes to it will be
   * reflected in this instance and vice-versa.
   */
  public org.json.JSONObject getJSONObject() {
    return genClient.getJSONObject();
  }


  @Override
  public void validate() {
  }

  /** Checks whether the 'ids' field is set and is not null */
  public boolean isNotNullIds() {
    return genClient.cacheValueIsNotNull(CacheKey.ids);
  }

  /** Checks whether the 'ids' field is set and is not null and is not empty */
  public boolean isNotEmptyIds() { return isNotNullIds() && !getIds().isEmpty(); }

  /** Checks whether the 'orderId' field is set and is not null */
  public boolean isNotNullOrderId() {
    return genClient.cacheValueIsNotNull(CacheKey.orderId);
  }


  /** Checks whether the 'ids' field has been set, however the value could be null */
  public boolean hasIds() {
    return genClient.cacheHasKey(CacheKey.ids);
  }

  /** Checks whether the 'orderId' field has been set, however the value could be null */
  public boolean hasOrderId() {
    return genClient.cacheHasKey(CacheKey.orderId);
  }


  /**
   * Sets the field 'ids'.
   *
   * Nulls in the given List are skipped. List parameter is copied, so it will not reflect any changes, but objects inside it will.
   */
  public LineItemsDeletedOperation setIds(java.util.List<String> ids) {
    return genClient.setArrayOther(ids, CacheKey.ids);
  }

  /**
   * Sets the field 'orderId'.
   */
  public LineItemsDeletedOperation setOrderId(String orderId) {
    return genClient.setOther(orderId, CacheKey.orderId);
  }


  /** Clears the 'ids' field, the 'has' method for this field will now return false */
  public void clearIds() {
    genClient.clear(CacheKey.ids);
  }
  /** Clears the 'orderId' field, the 'has' method for this field will now return false */
  public void clearOrderId() {
    genClient.clear(CacheKey.orderId);
  }


  /**
   * Returns true if this instance has any changes.
   */
  public boolean containsChanges() {
    return genClient.containsChanges();
  }

  /**
   * Reset the log of changes made to this instance, calling copyChanges() after this would return an empty instance.
   */
  public void resetChangeLog() {
    genClient.resetChangeLog();
  }

  /**
   * Create a copy of this instance that contains only fields that were set after the constructor was called.
   */
  public LineItemsDeletedOperation copyChanges() {
    LineItemsDeletedOperation copy = new LineItemsDeletedOperation();
    copy.mergeChanges(this);
    copy.resetChangeLog();
    return copy;
  }

  /**
   * Copy all the changed fields from the given source to this instance.
   */
  public void mergeChanges(LineItemsDeletedOperation src) {
    if (src.genClient.getChangeLog() != null) {
      genClient.mergeChanges(new LineItemsDeletedOperation(src).getJSONObject(), src.genClient);
    }
  }

  /**
   * Gets a Bundle which can be used to get and set data attached to this instance. The attached Bundle will be
   * parcelled but not jsonified.
   */
  public android.os.Bundle getBundle() {
    return genClient.getBundle();
  }

  @Override
  public String toString() {
    return genClient.toString();
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {
    genClient.writeToParcel(dest, flags);
  }

  public static final android.os.Parcelable.Creator<LineItemsDeletedOperation> CREATOR = new android.os.Parcelable.Creator<LineItemsDeletedOperation>() {
    @Override
    public LineItemsDeletedOperation createFromParcel(android.os.Parcel in) {
      LineItemsDeletedOperation instance = new LineItemsDeletedOperation(com.clover.sdk.v3.JsonParcelHelper.ObjectWrapper.CREATOR.createFromParcel(in).unwrap());
      instance.genClient.setBundle(in.readBundle(getClass().getClassLoader()));
      instance.genClient.setChangeLog(in.readBundle());
      return instance;
    }

    @Override
    public LineItemsDeletedOperation[] newArray(int size) {
      return new LineItemsDeletedOperation[size];
    }
  };

  public static final com.clover.sdk.JSONifiable.Creator<LineItemsDeletedOperation> JSON_CREATOR = new com.clover.sdk.JSONifiable.Creator<LineItemsDeletedOperation>() {
    @Override
    public LineItemsDeletedOperation create(org.json.JSONObject jsonObject) {
      return new LineItemsDeletedOperation(jsonObject);
    }
  };


  public interface Constraints {

    public static final boolean IDS_IS_REQUIRED = false;

    public static final boolean ORDERID_IS_REQUIRED = false;

  }

}
